### ISSUE TITLE
License file? 

### ISSUE THREAD

**Issue by gciccarelli3** [1000mileworld/Piano-Keyboard#1]
Good Evening,
Thank you for generously sharing your knowledge via freecodecamp.  I was wondering, would you be open to attaching a license to your code, just for clarity?  Keith, with audiosynth.js used an MIT license for example.  Apache 2.0 is also in the spirit of MIT and is actually more precise  (lots of Google's open source code is Apache 2.0).
Thank you.

**Comment by 1000mileworld** [comment]
Sure, I just added an MIT license.

**Comment by gciccarelli3** [comment]
Thanks.  As an fyi, I was browsing further around free code camp and code
on their site is under bsd 3 clause. Also a friendly choice.
https://www.freecodecamp.org/news/about/
https://snyk.io/blog/mit-apache-bsd-fairest-of-them-all/
Take care.
